### ISSUE TITLE
Namespace conflict

### ISSUE THREAD

**Issue by KarlikB** [adubkov/py-zabbix#132]
The "py-zabbix" library conflicts with "pyzabbix" library.

https://pypi.org/project/py-zabbix/
https://pypi.org/project/pyzabbix/

Both libraries writes into directory "pyzabbix" and effectively overwrites each other after pip install.

I have some code based on (other) "pyzabbix" library that does not support Zabbix Sender.
Now I need to add zabbix sender functionality but I do not wan to rewrite my old code for the new py-zabbix library, this is not currently possible.

The issue can be fixed by renaming the directory to "py-zabbix" as package name suggest.

**Comment by adubkov** [comment]
I don't think python allow use dashes in module name. This is common convention to name modules.

What I mean: you can't do:
```python
import py-zabbix
...
```

**Comment by KarlikB** [comment]
Thanks for response.

I am python beginner, but according https://www.python.org/dev/peps/pep-0420/#namespace-packages-today

it is possible to use variant "py_zabbix"

regards!

**Comment by adubkov** [comment]
Here is a thing - even if I could change module name to `py_zabbix`, we still will have to keep support for `pyzabbix` name, for backward compatibility as I did before (`zabbix` to `pyzabbix`). Reason for that is because this module used in many systems and pipelines so perform not compatible changes will break many things. 
So, it won't solve your issue, you may need do your own workaround for that.

**Comment by KarlikB** [comment]
Ok, I understand
